// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Collection struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	AuthorID string   `json:"authorId"`
	Author   *User    `json:"author"`
	NftIds   []string `json:"nftIds"`
	Nfts     []*Nft   `json:"nfts"`
}

type Nft struct {
	ID       string `json:"id"`
	Address  string `json:"address"`
	TokenID  string `json:"tokenId"`
	TokenURI string `json:"tokenURI"`
}

type NewCollection struct {
	Name     string   `json:"name"`
	AuthorID string   `json:"authorId"`
	Nfts     []string `json:"nfts"`
}

type NewCollectionNft struct {
	ID string `json:"id"`
}

type NewNft struct {
	Address string `json:"address"`
	TokenID string `json:"tokenId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
